# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='raw')),
                ('person_hints', models.CharField(max_length=512)),
                ('notes', models.CharField(max_length=512)),
            ],
        ),
    ]
