# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-29 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HarvestFaces', '0006_rawface'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawface',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rawface',
            name='width',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rawface',
            name='x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rawface',
            name='y',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rawface',
            name='image',
            field=models.FileField(upload_to='raw'),
        ),
        migrations.AlterField(
            model_name='rawimage',
            name='harvest_id',
            field=models.CharField(default=-1, max_length=512),
        ),
    ]
